export declare const alphabets: {
    cyrillic: string;
    english: string;
    latin: string;
    japanese: string;
    zh_sim: string;
    korean: string;
    telugu: string;
    kannada: string;
};
/**
 * Mapping of language codes to their corresponding symbol sets.
 */
export declare const symbols: {
    abq: string;
    ady: string;
    af: string;
    ava: string;
    az: string;
    be: string;
    bg: string;
    bs: string;
    chSim: string;
    che: string;
    cs: string;
    cy: string;
    da: string;
    dar: string;
    de: string;
    en: string;
    es: string;
    et: string;
    fr: string;
    ga: string;
    hr: string;
    hu: string;
    id: string;
    inh: string;
    ic: string;
    it: string;
    ja: string;
    kbd: string;
    kn: string;
    ko: string;
    ku: string;
    la: string;
    lbe: string;
    lez: string;
    lt: string;
    lv: string;
    mi: string;
    mn: string;
    ms: string;
    mt: string;
    nl: string;
    no: string;
    oc: string;
    pi: string;
    pl: string;
    pt: string;
    ro: string;
    ru: string;
    rsCyrillic: string;
    rsLatin: string;
    sk: string;
    sl: string;
    sq: string;
    sv: string;
    sw: string;
    tab: string;
    te: string;
    tjk: string;
    tl: string;
    tr: string;
    uk: string;
    uz: string;
    vi: string;
};
