"use strict";

export const IMAGENET1K_MEAN = [0.485, 0.456, 0.406];
export const IMAGENET1K_STD = [0.229, 0.224, 0.225];

/**
 * COCO dataset class labels used for object detection.
 *
 * @category Types
 */
export let CocoLabel = /*#__PURE__*/function (CocoLabel) {
  CocoLabel[CocoLabel["PERSON"] = 1] = "PERSON";
  CocoLabel[CocoLabel["BICYCLE"] = 2] = "BICYCLE";
  CocoLabel[CocoLabel["CAR"] = 3] = "CAR";
  CocoLabel[CocoLabel["MOTORCYCLE"] = 4] = "MOTORCYCLE";
  CocoLabel[CocoLabel["AIRPLANE"] = 5] = "AIRPLANE";
  CocoLabel[CocoLabel["BUS"] = 6] = "BUS";
  CocoLabel[CocoLabel["TRAIN"] = 7] = "TRAIN";
  CocoLabel[CocoLabel["TRUCK"] = 8] = "TRUCK";
  CocoLabel[CocoLabel["BOAT"] = 9] = "BOAT";
  CocoLabel[CocoLabel["TRAFFIC_LIGHT"] = 10] = "TRAFFIC_LIGHT";
  CocoLabel[CocoLabel["FIRE_HYDRANT"] = 11] = "FIRE_HYDRANT";
  CocoLabel[CocoLabel["STREET_SIGN"] = 12] = "STREET_SIGN";
  CocoLabel[CocoLabel["STOP_SIGN"] = 13] = "STOP_SIGN";
  CocoLabel[CocoLabel["PARKING"] = 14] = "PARKING";
  CocoLabel[CocoLabel["BENCH"] = 15] = "BENCH";
  CocoLabel[CocoLabel["BIRD"] = 16] = "BIRD";
  CocoLabel[CocoLabel["CAT"] = 17] = "CAT";
  CocoLabel[CocoLabel["DOG"] = 18] = "DOG";
  CocoLabel[CocoLabel["HORSE"] = 19] = "HORSE";
  CocoLabel[CocoLabel["SHEEP"] = 20] = "SHEEP";
  CocoLabel[CocoLabel["COW"] = 21] = "COW";
  CocoLabel[CocoLabel["ELEPHANT"] = 22] = "ELEPHANT";
  CocoLabel[CocoLabel["BEAR"] = 23] = "BEAR";
  CocoLabel[CocoLabel["ZEBRA"] = 24] = "ZEBRA";
  CocoLabel[CocoLabel["GIRAFFE"] = 25] = "GIRAFFE";
  CocoLabel[CocoLabel["HAT"] = 26] = "HAT";
  CocoLabel[CocoLabel["BACKPACK"] = 27] = "BACKPACK";
  CocoLabel[CocoLabel["UMBRELLA"] = 28] = "UMBRELLA";
  CocoLabel[CocoLabel["SHOE"] = 29] = "SHOE";
  CocoLabel[CocoLabel["EYE"] = 30] = "EYE";
  CocoLabel[CocoLabel["HANDBAG"] = 31] = "HANDBAG";
  CocoLabel[CocoLabel["TIE"] = 32] = "TIE";
  CocoLabel[CocoLabel["SUITCASE"] = 33] = "SUITCASE";
  CocoLabel[CocoLabel["FRISBEE"] = 34] = "FRISBEE";
  CocoLabel[CocoLabel["SKIS"] = 35] = "SKIS";
  CocoLabel[CocoLabel["SNOWBOARD"] = 36] = "SNOWBOARD";
  CocoLabel[CocoLabel["SPORTS"] = 37] = "SPORTS";
  CocoLabel[CocoLabel["KITE"] = 38] = "KITE";
  CocoLabel[CocoLabel["BASEBALL"] = 39] = "BASEBALL";
  CocoLabel[CocoLabel["SKATEBOARD"] = 41] = "SKATEBOARD";
  CocoLabel[CocoLabel["SURFBOARD"] = 42] = "SURFBOARD";
  CocoLabel[CocoLabel["TENNIS_RACKET"] = 43] = "TENNIS_RACKET";
  CocoLabel[CocoLabel["BOTTLE"] = 44] = "BOTTLE";
  CocoLabel[CocoLabel["PLATE"] = 45] = "PLATE";
  CocoLabel[CocoLabel["WINE_GLASS"] = 46] = "WINE_GLASS";
  CocoLabel[CocoLabel["CUP"] = 47] = "CUP";
  CocoLabel[CocoLabel["FORK"] = 48] = "FORK";
  CocoLabel[CocoLabel["KNIFE"] = 49] = "KNIFE";
  CocoLabel[CocoLabel["SPOON"] = 50] = "SPOON";
  CocoLabel[CocoLabel["BOWL"] = 51] = "BOWL";
  CocoLabel[CocoLabel["BANANA"] = 52] = "BANANA";
  CocoLabel[CocoLabel["APPLE"] = 53] = "APPLE";
  CocoLabel[CocoLabel["SANDWICH"] = 54] = "SANDWICH";
  CocoLabel[CocoLabel["ORANGE"] = 55] = "ORANGE";
  CocoLabel[CocoLabel["BROCCOLI"] = 56] = "BROCCOLI";
  CocoLabel[CocoLabel["CARROT"] = 57] = "CARROT";
  CocoLabel[CocoLabel["HOT_DOG"] = 58] = "HOT_DOG";
  CocoLabel[CocoLabel["PIZZA"] = 59] = "PIZZA";
  CocoLabel[CocoLabel["DONUT"] = 60] = "DONUT";
  CocoLabel[CocoLabel["CAKE"] = 61] = "CAKE";
  CocoLabel[CocoLabel["CHAIR"] = 62] = "CHAIR";
  CocoLabel[CocoLabel["COUCH"] = 63] = "COUCH";
  CocoLabel[CocoLabel["POTTED_PLANT"] = 64] = "POTTED_PLANT";
  CocoLabel[CocoLabel["BED"] = 65] = "BED";
  CocoLabel[CocoLabel["MIRROR"] = 66] = "MIRROR";
  CocoLabel[CocoLabel["DINING_TABLE"] = 67] = "DINING_TABLE";
  CocoLabel[CocoLabel["WINDOW"] = 68] = "WINDOW";
  CocoLabel[CocoLabel["DESK"] = 69] = "DESK";
  CocoLabel[CocoLabel["TOILET"] = 70] = "TOILET";
  CocoLabel[CocoLabel["DOOR"] = 71] = "DOOR";
  CocoLabel[CocoLabel["TV"] = 72] = "TV";
  CocoLabel[CocoLabel["LAPTOP"] = 73] = "LAPTOP";
  CocoLabel[CocoLabel["MOUSE"] = 74] = "MOUSE";
  CocoLabel[CocoLabel["REMOTE"] = 75] = "REMOTE";
  CocoLabel[CocoLabel["KEYBOARD"] = 76] = "KEYBOARD";
  CocoLabel[CocoLabel["CELL_PHONE"] = 77] = "CELL_PHONE";
  CocoLabel[CocoLabel["MICROWAVE"] = 78] = "MICROWAVE";
  CocoLabel[CocoLabel["OVEN"] = 79] = "OVEN";
  CocoLabel[CocoLabel["TOASTER"] = 80] = "TOASTER";
  CocoLabel[CocoLabel["SINK"] = 81] = "SINK";
  CocoLabel[CocoLabel["REFRIGERATOR"] = 82] = "REFRIGERATOR";
  CocoLabel[CocoLabel["BLENDER"] = 83] = "BLENDER";
  CocoLabel[CocoLabel["BOOK"] = 84] = "BOOK";
  CocoLabel[CocoLabel["CLOCK"] = 85] = "CLOCK";
  CocoLabel[CocoLabel["VASE"] = 86] = "VASE";
  CocoLabel[CocoLabel["SCISSORS"] = 87] = "SCISSORS";
  CocoLabel[CocoLabel["TEDDY_BEAR"] = 88] = "TEDDY_BEAR";
  CocoLabel[CocoLabel["HAIR_DRIER"] = 89] = "HAIR_DRIER";
  CocoLabel[CocoLabel["TOOTHBRUSH"] = 90] = "TOOTHBRUSH";
  CocoLabel[CocoLabel["HAIR_BRUSH"] = 91] = "HAIR_BRUSH";
  return CocoLabel;
}({});
//# sourceMappingURL=commonVision.js.map